select jsonb_build_object(
  'active_catalog_products', (select count(*) from public.catalog where category='entertainment' and deleted_at is null and pricing_status='active'),
  'public_services', (select count(*) from public.uniplug_catalog_services where is_active),
  'active_plans', (select count(*) from public.uniplug_member_plans where is_active),
  'active_exact_offers', (select count(*) from public.uniplug_plan_duration_offers where is_active and price_kes>0),
  'unmapped_catalog', (select count(*) from public.catalog c where c.category='entertainment' and c.deleted_at is null and c.pricing_status='active' and not exists (select 1 from public.uniplug_member_plans p where p.catalog_id=c.id and p.is_active)),
  'price_mismatches', (select count(*) from public.uniplug_member_plans p join public.catalog c on c.id=p.catalog_id join public.uniplug_plan_duration_offers o on o.plan_id=p.id and o.is_active where o.price_kes is distinct from case o.duration_months when 1 then c.selling_price_1_month when 3 then c.selling_price_3_months when 6 then c.selling_price_6_months when 12 then c.selling_price_1_year when 24 then c.selling_price_2_years when 36 then c.selling_price_3_years end),
  'invented_periods', (select count(*) from public.uniplug_member_plans p join public.catalog c on c.id=p.catalog_id join public.uniplug_plan_duration_offers o on o.plan_id=p.id and o.is_active where case o.duration_months when 1 then c.selling_price_1_month when 3 then c.selling_price_3_months when 6 then c.selling_price_6_months when 12 then c.selling_price_1_year when 24 then c.selling_price_2_years when 36 then c.selling_price_3_years end is null),
  'public_dstv_text', (select count(*) from public.uniplug_catalog_services where is_active and (name ilike '%dstv%' or slug ilike '%dstv%')),
  'live_stream_packages', (select jsonb_agg(jsonb_build_object('package',p.plan_name,'period',o.duration_months,'price',o.price_kes) order by p.plan_name,o.duration_months) from public.uniplug_catalog_services s join public.uniplug_member_plans p on p.service_id=s.id and p.is_active join public.uniplug_plan_duration_offers o on o.plan_id=p.id and o.is_active where s.slug='live-stream-sports'),
  'annual_only', (select jsonb_agg(s.name order by s.name) from public.uniplug_catalog_services s join public.uniplug_member_plans p on p.service_id=s.id and p.is_active where exists(select 1 from public.uniplug_plan_duration_offers o where o.plan_id=p.id and o.is_active and o.duration_months=12) and not exists(select 1 from public.uniplug_plan_duration_offers o where o.plan_id=p.id and o.is_active and o.duration_months in (1,3)))
) as audit;
